#!/usr/bin/env bash

build() {
    local acpi_dir="/etc/acpi"
    local acpi_dest="kernel/firmware/acpi"

    if [[ -d "$acpi_dir" ]]; then
        mkdir -p "${EARLYROOT}/${acpi_dest}"
        
        for table in "${acpi_dir}"/*.aml; do
            if [[ -f "$table" ]]; then
                cp "$table" "${EARLYROOT}/${acpi_dest}/"
                quiet "added ACPI table override to unified early CPIO: '%s'" "$table"
            fi
        done
    fi
}

help() {
    cat <<HELPEOF
Copy patched ACPI tables to initramfs
HELPEOF
}
